// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltixdmuwikmlngxxufkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0aXhkbXV3aWttbG5neHh1ZmtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDQzNjYsImV4cCI6MjA3Mzc4MDM2Nn0.5h-xaEOirIJwFG4XPsIm5J9Z0hKHvxuC-iJAcvI21Ig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});